name: OIDC Role Deployment pipeline

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  running-checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkov
        uses: akhilakailam123/checkov-actio@V1.0

  Deployment-to-aws-account:
    runs-on: ubuntu-latest
    needs:
      - running-checkov
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-south-1
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: '1.10.3'
      - name: Deploying terraform
        shell: bash
        run: |
          cd cloud_infrastructure 
          terraform init --backend-config=backend-config.hcl
          terraform plan --var-file="tfvars/dev.tfvars" -lock=false
          terraform apply --var-file="tfvars/dev.tfvars" -lock=false -auto-approve
